name: Build LdWrapper

on:
  push:
    branches: [ MaikoTS ]
  pull_request:
    branches: [ MaikoTS ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Android NDK
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV

      - name: Build libldwrapper.so
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libldwrapper
          path: libldwrapper.so
